---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ylrdxapi/rvctf.com
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R challenges $DEPLOYPATH
    